---
mailinglist:
  mailman_listinfo_url: 'https://lists.okfn.org/mailman/listinfo/codeforruhrgebiet'
  slug: 'codeforruhrgebiet'
  email: 'your-email-address-in-mailinglist'
  password: 'your-mailinglist-password'
meetup:
  api_key: 'put-meetup-key-here'
  group_slug: 'OK-Lab-Ruhrgebiet'
twitter:
  consumer_key: 'consumer_key here'
  consumer_secret: 'consumer_secret here'
  access_token: 'access_token here'
  access_token_secret: 'access_token_secret here'
  screen_name: 'codeforruhr'
facebook:
  sharebutton_url: 'https://www.facebook.com/v2.5/plugins/like.php?app_id=113869198637480&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D42%23cb%3Df1acc47a6530e2a%26domain%3Ddevelopers.facebook.com%26origin%3Dhttps%253A%252F%252Fdevelopers.facebook.com%252Ff24a252c615252c%26relation%3Dparent.parent&container_width=613&href=https%3A%2F%2Fwww.facebook.com%2Fcodeforruhrgebiet&layout=button_count&locale=de_DE&sdk=joey&share=false&show_faces=false'
